
SwatterData = {
	["enabled"] = true,
	["warning"] = true,
	["combat"] = false,
	["errors"] = {
		{
			["message"] = "Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)",
			["count"] = 7,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AucAdvanced, v8.2.6430 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6399 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  BagBrother, v\n  BagFreeSpaceCounter, v1.0.3\n  Bagnon, v8.3.1\n  BagnonConfig, v\n  BeanCounter, v8.2.6434 (SwimmingSeadragon)\n  BetterVendorPrice, vv1.11.00\n  CallbackHandler10, v\n  CantHealYou, v3.44\n  ClassicGuildBank, v1.3\n  ClassicTargetHelper, v\n  DBMCore, v1.13.30\n  DBMCountPackOverwatch, v1.4.9\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Decursive, v2.7.6.6\n  Details, v\n  DetailsStreamer, v\n  DetailsTinyThreat, v\n  Enchantrix, v8.2.6428 (SwimmingSeadragon)\n  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)\n  FastGuildInvite, v61\n  GatherMate2, v1.45.5\n  GTFO, v4.52\n  GuildRosterManager, v1.831\n  HealBot, v1.13.3.4\n  HealBotData, v1.13.3.4\n  HealBoten, v1.13.3.4\n  HealBotOptions, v1.13.3.4\n  HealBotTips, v1.13.3.4\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  LFGHelper, v1.0.2\n  LibStub, v\n  ModernQuestWatch, v1.0.9\n  Quester, v1.13.2.1\n  Questie, v5.5.1\n  Scrap, v8.3.0\n  ScrapConfig, v\n  SexyMap, vv5-classic\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Spy, v1.0.21\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TidyPlatesThreatPlates, v1.2.8\n  TomTom, vv11303-1.0.9\n  TradeSkillMaster, vv4.9.22\n  TradeSkillMasterAppHelper, vv4.0.7\n  BlizRuntimeLib_enUS v1.13.3.11303 <none>\n  (ck=67a)\n",
			["locals"] = "errMsg = \"Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)\"\ntsmErrMsg = nil\noldModule = nil\nprivate = <table> {\n CreateErrorFrame = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:514\n num = 0\n ErrorHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:132\n hitInternalError = false\n origErrorHandler = <function> defined @Interface\\AddOns\\Decursive\\Dcr_DIAG.lua:597\n FormatErrorMessageSection = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:495\n AddonBlockedHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:480\n SanitizeString = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:488\n GetStackLevelInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:328\n ParseLocals = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:380\n errorReports = <table> {\n }\n IsTSMAddon = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:456\n localLinesTemp = <table> {\n }\n GetStackInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:297\n}\nMAX_STACK_DEPTH = 50\nOLD_TSM_MODULES = <table> {\n 1 = \"TradeSkillMaster_Accounting\"\n 2 = \"TradeSkillMaster_AuctionDB\"\n 3 = \"TradeSkillMaster_Auctioning\"\n 4 = \"TradeSkillMaster_Crafting\"\n 5 = \"TradeSkillMaster_Destroying\"\n 6 = \"TradeSkillMaster_Mailing\"\n 7 = \"TradeSkillMaster_Shopping\"\n 8 = \"TradeSkillMaster_Vendoring\"\n 9 = \"TradeSkillMaster_Warehousing\"\n}\n",
			["timestamp"] = "2020-02-08 21:33:07",
			["context"] = "Global",
			["stack"] = "...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:733: in function <...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:693>\n[C]: ?\nInterface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: in function <Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1181>\n",
		}, -- [1]
		{
			["message"] = "Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)",
			["count"] = 5,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AucAdvanced, v8.2.6430 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucScanData, v8.2.6365 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6399 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  BagBrother, v\n  BagFreeSpaceCounter, v1.0.3\n  Bagnon, v8.3.1\n  BeanCounter, v8.2.6434 (SwimmingSeadragon)\n  BetterVendorPrice, vv1.11.00\n  CallbackHandler10, v\n  CantHealYou, v3.44\n  ClassicGuildBank, v1.3\n  ClassicTargetHelper, v\n  DBMCore, v1.13.30\n  DBMCountPackOverwatch, v1.4.9\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Decursive, v2.7.6.6\n  Details, v\n  DetailsStreamer, v\n  DetailsTinyThreat, v\n  Enchantrix, v8.2.6428 (SwimmingSeadragon)\n  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)\n  FastGuildInvite, v61\n  GatherMate2, v1.45.5\n  GTFO, v4.52\n  GuildRosterManager, v1.831\n  HealBot, v1.13.3.4\n  HealBotData, v1.13.3.4\n  HealBoten, v1.13.3.4\n  HealBotOptions, v1.13.3.4\n  HealBotTips, v1.13.3.4\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  LFGHelper, v1.0.2\n  LibStub, v\n  ModernQuestWatch, v1.0.9\n  Quester, v1.13.2.1\n  Questie, v5.5.1\n  Scrap, v8.3.0\n  SexyMap, vv5-classic\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Spy, v1.0.21\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TidyPlatesThreatPlates, v1.2.8\n  TomTom, vv11303-1.0.9\n  TradeSkillMaster, vv4.9.25\n  TradeSkillMasterAppHelper, vv4.0.7\n  BlizRuntimeLib_enUS v1.13.3.11303 <none>\n  (ck=657)\n",
			["locals"] = "errMsg = \"Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)\"\ntsmErrMsg = nil\noldModule = nil\nprivate = <table> {\n CreateErrorFrame = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:514\n num = 0\n ErrorHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:132\n hitInternalError = false\n origErrorHandler = <function> defined @Interface\\AddOns\\Decursive\\Dcr_DIAG.lua:597\n FormatErrorMessageSection = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:495\n AddonBlockedHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:480\n SanitizeString = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:488\n GetStackLevelInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:328\n ParseLocals = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:380\n errorReports = <table> {\n }\n IsTSMAddon = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:456\n localLinesTemp = <table> {\n }\n GetStackInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:297\n}\nMAX_STACK_DEPTH = 50\nOLD_TSM_MODULES = <table> {\n 1 = \"TradeSkillMaster_Accounting\"\n 2 = \"TradeSkillMaster_AuctionDB\"\n 3 = \"TradeSkillMaster_Auctioning\"\n 4 = \"TradeSkillMaster_Crafting\"\n 5 = \"TradeSkillMaster_Destroying\"\n 6 = \"TradeSkillMaster_Mailing\"\n 7 = \"TradeSkillMaster_Shopping\"\n 8 = \"TradeSkillMaster_Vendoring\"\n 9 = \"TradeSkillMaster_Warehousing\"\n}\n",
			["timestamp"] = "2020-02-11 20:31:12",
			["context"] = "Global",
			["stack"] = "...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:733: in function <...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:693>\n[C]: ?\nInterface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: in function <Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1181>\n",
		}, -- [2]
		{
			["message"] = "Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6377 (SwimmingSeadragon)\n  AucAdvanced, v8.2.6430 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6399 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)\n  BagBrother, v\n  BagFreeSpaceCounter, v1.0.3\n  Bagnon, v8.3.1\n  BeanCounter, v8.2.6434 (SwimmingSeadragon)\n  BetterVendorPrice, vv1.11.00\n  CallbackHandler10, v\n  CantHealYou, v3.44\n  ClassicGuildBank, v1.3\n  ClassicTargetHelper, v\n  DBMCore, v1.13.30\n  DBMCountPackOverwatch, v1.4.9\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Decursive, v2.7.6.6\n  Details, v\n  DetailsStreamer, v\n  DetailsTinyThreat, v\n  Enchantrix, v8.2.6428 (SwimmingSeadragon)\n  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)\n  FastGuildInvite, v61\n  GatherMate2, v1.45.5\n  GTFO, v4.52\n  GuildRosterManager, v1.831\n  HealBot, v1.13.3.4\n  HealBotData, v1.13.3.4\n  HealBoten, v1.13.3.4\n  HealBotOptions, v1.13.3.4\n  HealBotTips, v1.13.3.4\n  Informant, v8.2.6374 (SwimmingSeadragon)\n  LFGHelper, v1.0.2\n  LibStub, v\n  ModernQuestWatch, v1.0.9\n  Quester, v1.13.2.1\n  Questie, v5.5.1\n  Scrap, v8.3.0\n  SexyMap, vv5-classic\n  SlideBar, v8.2.6375 (SwimmingSeadragon)\n  Spy, v1.0.21\n  Stubby, v8.2.6376 (SwimmingSeadragon)\n  TidyPlatesThreatPlates, v1.2.8\n  TomTom, vv11303-1.0.9\n  TradeSkillMaster, vv4.9.25\n  TradeSkillMasterAppHelper, vv4.0.7\n  BlizRuntimeLib_enUS v1.13.3.11303 <none>\n  (ck=62a)\n",
			["locals"] = "errMsg = \"Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: attempt to index global 'LFG_Notifications' (a nil value)\"\ntsmErrMsg = nil\noldModule = nil\nprivate = <table> {\n CreateErrorFrame = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:514\n num = 0\n ErrorHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:132\n hitInternalError = false\n origErrorHandler = <function> defined @Interface\\AddOns\\Decursive\\Dcr_DIAG.lua:597\n FormatErrorMessageSection = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:495\n AddonBlockedHandler = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:480\n SanitizeString = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:488\n GetStackLevelInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:328\n ParseLocals = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:380\n errorReports = <table> {\n }\n IsTSMAddon = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:456\n localLinesTemp = <table> {\n }\n GetStackInfo = <function> defined @Interface\\AddOns\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:297\n}\nMAX_STACK_DEPTH = 50\nOLD_TSM_MODULES = <table> {\n 1 = \"TradeSkillMaster_Accounting\"\n 2 = \"TradeSkillMaster_AuctionDB\"\n 3 = \"TradeSkillMaster_Auctioning\"\n 4 = \"TradeSkillMaster_Crafting\"\n 5 = \"TradeSkillMaster_Destroying\"\n 6 = \"TradeSkillMaster_Mailing\"\n 7 = \"TradeSkillMaster_Shopping\"\n 8 = \"TradeSkillMaster_Vendoring\"\n 9 = \"TradeSkillMaster_Warehousing\"\n}\n",
			["timestamp"] = "2020-02-11 20:53:51",
			["context"] = "Global",
			["stack"] = "...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:733: in function <...Ons\\TradeSkillMaster\\LibTSM\\Service\\ErrorHandler.lua:693>\n[C]: ?\nInterface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1333: in function <Interface\\AddOns\\LFG_Helper\\LFG_Helper.lua:1181>\n",
		}, -- [3]
	},
	["autoshow"] = true,
}
